name: timeline_widget_example
description: "The example of usage a timeline_widget"
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  horizontal_timeline: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
