name: horizontal_timeline
description: 'Draws a 24-hour time scale with 15-minute increments, allowing you to select a time range.'
version: 1.5.0
repository: https://github.com/AndreyKedo/timeline_widget

topics:
  - widget
  - timeline

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
